version: "3.8"

services:
  db:
    image: mongo:7.0
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db

  etl:
    build: . 
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    env_file:
      - .env 
    depends_on:
      - db 
    command: tail -f /dev/null

volumes:
  mongo_data:
