# ============================
# Mapping columns by domain
# ============================

COLUNAS_IDENTIFICACAO = [
    "NO_REGIAO", "SG_UF", "NO_MUNICIPIO", "CO_MUNICIPIO",
    "NO_ENTIDADE", "CO_ENTIDADE", "TP_DEPENDENCIA",
    "TP_LOCALIZACAO", "TP_LOCALIZACAO_DIFERENCIADA",
    "TP_SITUACAO_FUNCIONAMENTO",
    # Endereço completo — necessário para geocodificação e perfil da escola
    "DS_ENDERECO", "NU_ENDERECO", "NO_BAIRRO", "CO_CEP",
]

COLUNAS_INFRA = [
    "IN_AGUA_POTAVEL","IN_ENERGIA_REDE_PUBLICA","IN_ESGOTO_REDE_PUBLICA",
    "IN_LIXO_SERVICO_COLETA","IN_BIBLIOTECA","IN_LABORATORIO_INFORMATICA",
    "IN_LABORATORIO_CIENCIAS","IN_QUADRA_ESPORTES","IN_QUADRA_ESPORTES_COBERTA",
    "IN_COZINHA","IN_PISCINA","IN_REFEITORIO","IN_PATIO_COBERTO","IN_PATIO_DESCOBERTO"
]

COLUNAS_ACESSIBILIDADE = [
    "IN_ACESSIBILIDADE_CORRIMAO","IN_ACESSIBILIDADE_ELEVADOR",
    "IN_ACESSIBILIDADE_PISOS_TATEIS","IN_ACESSIBILIDADE_RAMPAS",
    "IN_ACESSIBILIDADE_SINAL_VISUAL","IN_ACESSIBILIDADE_SINAL_SONORO",
    "IN_ACESSIBILIDADE_SINAL_TATIL","IN_ACESSIBILIDADE_INEXISTENTE"
]

COLUNAS_TECNOLOGIA = [
    "IN_INTERNET","IN_INTERNET_ALUNOS","IN_INTERNET_ADMINISTRATIVO",
    "IN_EQUIP_IMPRESSORA","IN_EQUIP_LOUSA_DIGITAL","IN_EQUIP_MULTIMIDIA",
    "IN_DESKTOP_ALUNO","IN_COMP_PORTATIL_ALUNO","IN_TABLET_ALUNO"
]

COLUNAS_PROFISSIONAIS = [
    "QT_PROF_ADMINISTRATIVOS","QT_PROF_SERVICOS_GERAIS","QT_PROF_BIBLIOTECARIO",
    "QT_PROF_SAUDE","QT_PROF_COORDENADOR","QT_PROF_PEDAGOGIA","QT_PROF_SECRETARIO",
    "QT_PROF_SEGURANCA","QT_PROF_MONITORES","QT_PROF_ASSIST_SOCIAL"
]

COLUNAS_MATRICULAS = [
    "QT_MAT_INF","QT_MAT_INF_CRE","QT_MAT_INF_PRE","QT_MAT_FUND",
    "QT_MAT_FUND_AI","QT_MAT_FUND_AF","QT_MAT_MED","QT_MAT_MED_PROP",
    "QT_MAT_MED_CT","QT_MAT_MED_NM","QT_MAT_EJA","QT_MAT_EJA_FUND","QT_MAT_EJA_MED"
]

COLUNAS_DOCENTES = [
    "QT_DOC_INF","QT_DOC_FUND","QT_DOC_MED","QT_DOC_PROF","QT_DOC_EJA","QT_DOC_ESP"
]

COLUNAS_SALAS = [
    "QT_SALAS_UTILIZADAS","QT_SALAS_UTILIZA_CLIMATIZADAS",
    "QT_SALAS_UTILIZADAS_ACESSIVEIS"
]

COLUNAS_TRANSPORTE = [
    "QT_TRANSP_PUBLICO","QT_TRANSP_RESP_EST","QT_TRANSP_RESP_MUN"
]

# all gathered columns
COLUNAS_TOTAIS = (
    COLUNAS_IDENTIFICACAO +
    COLUNAS_INFRA +
    COLUNAS_ACESSIBILIDADE +
    COLUNAS_TECNOLOGIA +
    COLUNAS_PROFISSIONAIS +
    COLUNAS_MATRICULAS +
    COLUNAS_DOCENTES +
    COLUNAS_SALAS +
    COLUNAS_TRANSPORTE
)
