name: Discord Notifier

on:
    pull_request:
        types: [opened, reopened]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send notification to Discord
              uses: tsickert/discord-webhook@v5.5.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  content: "Heads up, @everyone! A new Pull Request is available for review."
                  embed-title: "${{ github.event.pull_request.title }}"
                  embed-url: "${{ github.event.pull_request.html_url }}"
                  embed-color: "65280"
                  embed-author-name: "${{ github.actor }}"
                  embed-author-url: "${{ github.server_url }}/${{ github.actor }}"
                  embed-author-icon-url: "${{ github.server_url }}/${{ github.actor }}.png?size=32"
                  embed-footer-text: "Project: ODIN | Automated Notification for ETL"
